### ISSUE TITLE
cluster commansd: PID

### ISSUE THREAD

**Issue by ElkeF** [ElkeF/tc_commands#10]
Hi,

You write:
- Sometimes you will realize a job you just submitted has some error. It is a good practice to kill it before starting a new one. Having a list with your PID's also helps in that task if your user is shared

What is a PID?

**Comment by ElkeF** [comment]
Nice information. You didn't address the question.

**Comment by behnle** [comment]
Ah, just realized that i only answered it in the pull request:
https://github.com/ElkeF/tc_commands/pull/23#issue-1061507719
and in the content committed.
A PID is a unique process identifier: https://en.wikipedia.org/wiki/Process_identifier
Anyway.
- On a (professional) cluster, you never ever work with shared users. Period. Adding a new user takes 10 seconds. Recovering accidentally deleted data takes 10 hours.
- On a cluster, you use the mechanisms of the queuing system to kill jobs.
What might be more relevant are thus job IDs, i.e. unique job numbers assigned by the queueing system when submitting a job.
