### ISSUE TITLE
remotely: EDI

### ISSUE THREAD

**Issue by ElkeF** [ElkeF/tc_commands#17]
Hi,

You write,

Know the IP address of your remote computer

How do I get that?

**Comment by behnle** [comment]
- If it is a cluster: Ask  your cluster admin or look it up on the university homepage describing the cluster.
Or better do not use IP addresses for accessing clusters when there are  globally valid host names. IP addresses may change over time and might not be unique.
- If it is a local machine: 
  - ask your supervisor or coworker
  - walk to the computer, log in, type `ip address show scope global` into a shell and read the four-block IPv4 address after "inet". On ancient machines use `ifconfig`.
