### ISSUE TITLE
Improving the documentation for the 'ls' command

### ISSUE THREAD

**Issue by EirikML** [ElkeF/tc_commands#25]
File: terminal_basics.txt

I find the documentation for the usage of the 'ls' command (line 17) is missing a critical point:
It is undocumented where and how to use the options (-l, -a, -h) in the command.

I suggest adding a short explanation on how to do this, to make it clearer for the reader.

**Comment by ElkeF** [comment]
I will take care of it and combine it with issue #5

**Comment by ElkeF** [comment]
@EirikML Please have a look at the closing commit. Does that help?

**Comment by EirikML** [comment]
@ElkeF Yes, I think it is much clearer now.
