### ISSUE TITLE
weird description in terminal_basics.txt

### ISSUE THREAD

**Issue by ElkeF** [ElkeF/tc_commands#6]
Hi,

You write:

all 1.) mkdir cookbook
the creates the directory cookbook
places
I 1a) for i in {25..45..1};do echo $i; mkdir $i; done
have creates the subdirectories 25, 26, 27, ..., 45
been

Why do you have the words "places" and "been"?

**Comment by ReinholdFink** [comment]
seems to be unnecessary. I'll take care of it.

**Comment by jhenrichsmeyer** [comment]
Maybe because you added them?
