### ISSUE TITLE
cluster commands: what do variables mean?

### ISSUE THREAD

**Issue by ElkeF** [ElkeF/tc_commands#9]
Hi,

You write

- an examplary submission script that submits a calculation
with a Python script named hello.py looks as follows:
#!/bin/sh
# Grid Engine options (lines prefixed with #$)
#$ -N hello              
#$ -cwd                  
#$ -l h_rt=00:05:00 
#$ -l h_vmem=1G
#  These options are:
#  job name: -N
#  use the current working directory: -cwd
#  runtime limit of 5 minutes: -l h_rt
#  memory limit of 1 Gbyte: -l h_vmem
# Initialise the environment modules
. /etc/profile.d/modules.sh
# Load Python
module load python/3.4.3
# Run the program
./hello.py

What do all these variables mean and which are save to change, and which are not?

**Comment by Simmermacher** [comment]
I will take care of it.

**Comment by behnle** [comment]
any updates on that one?

**Comment by Simmermacher** [comment]
Almost done.

**Comment by AMC-dyn** [comment]
Everything looks fine now!
